### ISSUE TITLE
yank a release

### ISSUE THREAD

**Issue by dcherian** [conda-forge/flox-feedstock#65]
### Comment:

I had a version typo: `09.11` instead of `0.9.11`. What's the best way to fix this on conda? I have yanked the pypi release and redone the release there.

**Comment by dcherian** [comment]
cc @jakirkham

**Comment by ocefpaf** [comment]
Done. See https://github.com/conda-forge/admin-requests/pull/1083

**Comment by ocefpaf** [comment]
Should be marked as broken. Please re-open if that did not work.

**Comment by dcherian** [comment]
Thanks!
